// ecdef.h : interface of the CEcDoc class
//

/////////////////////////////////////////////////////////////////////////////

//#define	iNNN	128000
//#define	NNN		512000


#define	M_CV	0
#define	M_LSV	1
#define	M_SCV	2
#define	M_TAFEL	3
#define	M_CA	4
#define	M_CC	5
#define	M_DPV	6
#define	M_NPV	7
#define	M_SWV	8
#define	M_ACV	9
#define	M_SHACV	10
#define	M_IT	11
#define	M_BE	12
#define M_HMV	13
#define M_IMP	14
#define	M_CP	15
#define M_PSA	16
#define M_IMPT	17
#define M_DPA	18
#define M_TPA	19
#define M_DDPA	20
#define M_CPCR	21
#define M_DNPV	22
#define M_SECM	23
#define M_PAC	24
#define M_PSC	25
#define M_OCPT	26
#define M_SSF	27
#define M_IMPE	28
#define M_STEP	29
#define M_QCM	30
#define M_SSTEP	31
#define M_CPCS	32
#define M_IPAD	33
#define M_SPC	34
#define M_SWG	35
#define M_SONIC	36
#define M_ECN	37
#define	M_SMPL	38
#define	M_SISECM	39
#define	M_LVDT	40
#define	M_FTACV	41
#define M_ZCCC	42
#define M_ICHRG	43












