//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by analyzer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_PLOT                        101
#define IDS_ANALYSIS_PROGRESS           102
#define IDS_STRING_RUNNING              103
#define IDS_STRING_WAIT_RESPONSE        104
#define IDS_STRING_OVER                 105
#define IDS_STRING_STEPNAME0            106
#define IDS_STRING_STEPNAME1            107
#define IDS_STRING_CYCLE                108
#define IDS_STRING_YES                  109
#define IDS_STRING_NO                   110
#define IDS_STRING111                   111
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDS_STRING114                   114
#define IDS_STRING_CHARGE_Q             115
#define IDS_STRING_NORMALIZED_Q         116
#define IDS_STRING117                   117
#define IDR_HELP_MENU                   118
#define IDS_STRING_READY                118
#define IDR_POPUP_EDIT                  119
#define IDS_STRING_OVER_SWITCH          119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_analyzerTYPE                130
#define IDS_STRING_STEP_ERROR           130
#define IDS_STRING_POTENTIAL            131
#define IDS_STRING_CURRENT              132
#define IDS_STRING_ERROR                133
#define IDS_STRING_SAVE_ERROR           134
#define IDS_STRING_SAP_TIPS             135
#define IDS_STRING_READ_ERROR           136
#define IDS_STRING_SAR                  137
#define IDS_STRING_REPORT               138
#define IDS_STRING_REPORTING            139
#define IDS_STRING_PAUSE                140
#define IDS_STRING_PARA_CHANGED         141
#define IDS_STRING_IS_SAVED             142
#define IDS_STRING_INVALID_USERNAME     143
#define IDS_STRING_WRONG_PASSWORD       144
#define IDS_STRING_OK                   145
#define IDS_STRING_RESUME               146
#define IDS_STRING_APPLY                147
#define ID_VIEW_OUTPUTWND               149
#define IDS_EDIT_TIPS                   150
#define IDS_STRING_ADD_SOLUTION         151
#define IDS_OUTPUT_WND                  157
#define IDS_STRING_CALIBRATION_CURVE    160
#define IDS_STRING_FITTING_LINE         161
#define IDS_STRING_TEST_CURVE           162
#define IDS_STRING_TEST_POINT           163
#define IDS_STRING_INTERCEPT_Q          164
#define IDI_OUTPUT_WND                  165
#define IDS_STRING_VOLTAMMOGRAM         165
#define IDI_OUTPUT_WND_HC               166
#define IDS_FILTER_GHB                  180
#define IDS_FILTER_PDF                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define IDS_STRING_LOW_E_LIMIT          200
#define ID_SET_STYLE                    201
#define IDS_STRING_HIGH_E_LIMIT         201
#define IDS_STRING_SCAN_RATE            202
#define IDS_STRING_ROTATION_RATE        203
#define IDS_STRING_VARIATION_TOLERANCE  204
#define ID_VIEW_APPLOOK_WIN_2000        205
#define IDS_STRING_NO_OF_CYCLES         205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define IDS_STRING_END_INTEGRATION_E    206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define IDS_STRING_START_INTEGRATION_E  207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDS_COMBO_CYCLE_TYPE            210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_VIEW_CAPTION_BAR             221
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_EDIT_LOW_E_LIMIT            256
#define IDS_EDIT_HIGH_E_LIMIT           257
#define IDS_EDIT_SCAN_RATE              258
#define IDS_EDIT_ROTATION_RATE          259
#define IDS_EDIT_VARIATION_TOLERANCE    260
#define IDS_EDIT_NO_OF_CYCLES           261
#define IDS_EDIT_END_INTEGRATION_E      262
#define IDS_EDIT_START_INTEGRATION_E    263
#define IDS_STRING_AUTO                 280
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_PROGRESS_TAB                303
#define IDS_EDIT_MENU                   306
#define IDR_LIST_POPUP                  311
#define IDR_LISTUA_POPUP                312
#define IDD_DIALOG4                     313
#define IDD_DIALOG_UAP                  313
#define IDB_BITMAP_ASTRI                331
#define IDB_BITMAP_SINYANG              332
#define IDD_DIALOG_LOGIN                333
#define IDI_ICON2                       340
#define IDI_ICON3                       341
#define IDI_ICON4                       342
#define IDD_DIALOG_START                350
#define IDB_BITMAP11                    351
#define IDD_DIALOG_WAIT                 351
#define IDD_DIALOG_COMPUTE              352
#define IDD_DIALOG_EXPORT               353
#define IDD_DIALOG_APP                  354
#define IDD_DIALOG_CVP                  355
#define IDB_BITMAP12                    356
#define IDD_DIALOG_SAP                  356
#define IDD_DIALOG_PSPB                 357
#define IDB_BITMAP13                    358
#define IDD_DIALOG_                     358
#define IDD_DIALOG_PSPC                 358
#define IDB_BITMAP14                    359
#define IDB_BITMAP15                    361
#define IDB_BITMAP16                    362
#define IDB_BITMAP17                    363
#define IDB_BITMAP18                    364
#define IDB_BITMAP19                    365
#define IDB_BITMAP_b                    366
#define IDB_BITMAP_bA                   367
#define IDB_BITMAP_bstd                 368
#define IDB_BITMAP_CL                   369
#define IDB_BITMAP_k                    370
#define IDB_BITMAP_kA                   371
#define IDB_BITMAP_kSAR                 372
#define IDB_BITMAP_mL                   373
#define IDB_BITMAP_q                    374
#define IDB_BITMAP_Qit                  375
#define IDB_BITMAP_Vb                   376
#define IDB_BITMAP_Vsp                  377
#define IDB_BITMAP_VspR                 378
#define IDB_BITMAP_Vtotal               379
#define IDB_BITMAP_z                    380
#define IDB_BITMAP_bSAR                 381
#define IDS_STRING_ANALYSIS_TYPE        400
#define IDS_STRING_EVALUATION_RATIO     401
#define IDS_STRING_ENDPOINT_RATIO       402
#define IDS_COMBO_CALIBRATION_TYPE      403
#define IDS_STRING_CALIBRATION_FACTOR   404
#define IDS_STRING_CALIBRATION_CURVE_FILE 405
#define IDS_STRING_INTERCEPT_VALUE      406
#define IDS_STRING_OPEN_CALIBRATION_FILE 407
#define IDS_COMBO_ANALYSIS_TYPE         430
#define IDS_EDIT_EVALUATION_RATIO       431
#define IDS_EDIT_ENDPOINT_RATIO         432
#define IDS_EDIT_CALIBRATION_FACTOR     433
#define IDS_EDIT_CALIBRATION_CURVE_FILE 434
#define IDS_EDIT_INTERCEPT_VALUE        435
#define IDS_EDIT_REMARK_ON_ANALYSIS_TYPE 450
#define IDS_STRING_AT1                  470
#define IDS_STRING_AT2                  471
#define IDS_STRING_AT3                  472
#define IDS_STRING_AT4                  473
#define IDS_STRING_AT5                  474
#define IDS_STRING_AT6                  475
#define IDS_STRING_AT7                  476
#define IDS_STRING_AT8                  477
#define IDS_STRING_AT9                  478
#define IDS_STRING_AT10                 479
#define IDS_STRING_AT11                 480
#define IDS_STRING_AT12                 481
#define IDS_STRING_AT13                 482
#define IDS_LISTCTRL_SAP                500
#define IDS_LISTCTRL_PSP                501
#define IDS_LISTCTRL_LSP                502
#define IDS_LISTCTRL_SAP_0              503
#define IDS_LISTCTRL_SAP_1              504
#define IDS_STRING510                   510
#define IDS_STRING511                   511
#define IDS_STRING_CONC_                512
#define IDS_STRING_VOL_                 513
#define IDS_STRING520                   520
#define IDS_STRING524                   521
#define IDS_STRING521                   522
#define IDS_STRING522                   523
#define IDS_STRING523                   524
#define IDS_STRING525                   525
#define IDS_STRING526                   526
#define IDS_STRING530                   530
#define IDS_STRING_SUPPRESSOR           531
#define IDS_STRING_ACCELERATOR          532
#define IDS_STRING_LEVELER              533
#define IDS_STRING_SAMPLE               534
#define IDS_STRING_S                    535
#define IDS_STRING_A                    536
#define IDS_STRING_L                    537
#define IDS_STRING_ML                   538
#define IDS_STRING_ML_PER_L             539
#define IDS_STRING_VOLUME               540
#define IDS_STRING_CONCERTRATION        541
#define IDS_STRING_VOL_ONCE             550
#define IDS_STRING_VOL_INTERVAL         551
#define IDS_STRING_CONC_ONCE            552
#define IDS_STRING_CONC_INTERVAL        553
#define IDS_STRING_VMS                  554
#define IDS_STRING_VIRGIN_MAKEUP        560
#define IDS_STRING_MIX                  561
#define IDS_STRING_VMS_VOLUME           570
#define IDS_EDIT_VMS_VOLUME             571
#define IDS_STRING_ANALYSIS_PARA        600
#define IDS_STRING_CV_PARA              601
#define IDS_STRING_ADDITION_SOLUTION_PARA 602
#define IDS_STRING_ANALYSIS_SETUP       603
#define IDS_EDIT_CAPTION_EDIT           620
#define IDS_BUTTON_CAPTION_CHECKBOX     621
#define IDS_STRING_POLT_SETTINGS        650
#define IDS_STRING_FIGURE1              651
#define IDS_STRING_FIGURE2              652
#define IDS_COMBO_FIGURE_SPEC           670
#define IDS_STRING_BKGND_BORDER_COLOR   671
#define IDS_STRING_GRID_LINE            672
#define IDS_STRING_LABEL                673
#define IDS_STRING_METRIC               674
#define IDS_STRING_XLABEL_YLABEL        675
#define IDS_COLOR_BORDER                681
#define IDS_COLOR_GRID_LINE             682
#define IDS_COLOR_LABEL                 683
#define IDS_COLOR_METRIC                684
#define IDS_EDIT_YLABEL                 685
#define IDS_STRING_GRID_LINE_SOLID      692
#define IDS_STRING_GRID_LINE_DASH       693
#define IDS_STRING_GRID_LINE_DOT        694
#define IDS_STRING_GRID_LINE_DASHDOT    695
#define IDS_STRING_GRID_LINE_DASHDOTDOT 696
#define IDS_STRING_GRID_LINE_HIDE       697
#define IDS_COLOR_BKGND                 700
#define IDS_COMBO_GRID_LINE_TYPE        701
#define IDS_EDIT_LABEL_SIZE             702
#define IDS_EDIT_METRIC_SIZE            703
#define IDS_EDIT_XLABEL                 704
#define IDS_STRING720                   720
#define IDS_STRING721                   721
#define IDS_STRING722                   722
#define IDS_STRING723                   723
#define IDS_STRING724                   724
#define IDS_STRING725                   725
#define IDS_STRING726                   726
#define IDS_STRING_NO_SMOOTH            740
#define IDS_STRING_CUBIC_SPLINE         741
#define IDS_STRING_BEZIER               742
#define IDS_STRING_SETUP_FILE_ERROR     750
#define IDS_STRING_COLOR_STYLE          770
#define IDS_STRING_GRID_LINE_TYPE       771
#define IDS_STRING_LABEL_SIZE           772
#define IDS_STRING_METRIC_SIZE          773
#define IDS_STRING774                   774
#define IDS_STRING775                   775
#define IDS_STRING776                   776
#define IDS_COMBO_COLOR_STYLE           790
#define IDS_EDIT_USERNAME               800
#define IDS_EDIT_PASSWORD               801
#define IDS_STRING_LOGIN                802
#define IDS_STRING_CANCEL               803
#define IDS_STRING_CLOSE1               804
#define IDS_STRING_HELP                 805
#define IDS_STRING_LIST_ACCOUNT         810
#define IDS_STRING_USER_ACCOUNT         811
#define IDS_STRING_USER_NAME            820
#define IDS_STRING_PASSWORD             821
#define IDS_STRING_TYPE                 822
#define IDS_STRING_ACTIVE               823
#define IDS_STRING_REMARK               824
#define IDS_STRING_ADMIN                835
#define IDS_STRING_USER                 836
#define IDS_STRING_GUEST                837
#define IDS_STRING_USERLIST_ERROR       850
#define IDS_STRING_USER_DEFINE          899
#define IDS_STRING_COLOR_TYPE_0         900
#define IDS_STRING_COLOR_TYPE_1         901
#define IDS_STRING_COLOR_TYPE_2         902
#define IDS_STRING_COLOR_TYPE_3         903
#define IDS_STRING904                   904
#define IDS_STRING905                   905
#define IDS_STRING906                   906
#define IDS_STRING907                   907
#define IDS_STRING908                   908
#define IDS_STRING909                   909
#define IDS_STRING910                   910
#define IDS_STRING911                   911
#define IDS_STRING912                   912
#define IDS_STRING913                   913
#define IDS_STRING914                   914
#define IDS_STRING915                   915
#define IDS_STRING916                   916
#define IDS_STRING917                   917
#define IDS_STRING918                   918
#define IDS_STRING919                   919
#define IDS_STRING920                   920
#define IDS_STRING921                   921
#define IDS_STRING922                   922
#define IDS_STRING923                   923
#define IDS_STRING924                   924
#define IDS_STRING925                   925
#define IDS_STRING926                   926
#define IDS_STRING927                   927
#define IDS_STRING928                   928
#define IDS_STRING929                   929
#define IDS_STRING930                   930
#define IDS_STRING931                   931
#define IDS_STRING932                   932
#define IDS_STRING933                   933
#define IDS_STRING934                   934
#define IDS_STRING935                   935
#define IDS_STRING936                   936
#define IDS_STRING937                   937
#define IDS_STRING938                   938
#define IDS_STRING939                   939
#define IDS_STRING940                   940
#define IDS_STRING941                   941
#define IDS_CHECK_ANALYSIS_PARA         1000
#define IDS_CHECK_SHOW_LEGEND           1100
#define IDS_STRING_ALIGNMENT            1101
#define IDS_CHECK_FIX_LOCATION          1102
#define IDS_COMBO_ADJUST                1103
#define IDS_STRING_W_H                  1104
#define IDS_STRING_FONT_SIZE            1104
#define IDS_STRING_FS_LL                1105
#define IDS_STRING_LINE_LENGTH          1105
#define IDS_EDIT_WIDTH                  1106
#define IDS_EDIT_HEIGHT                 1107
#define IDS_EDIT_FONT_SIZE              1108
#define IDS_EDIT_LINE_LENGTH            1109
#define IDS_STRING_FREE                 1110
#define IDS_STRING1111                  1111
#define IDS_STRING1112                  1112
#define IDS_STRING1113                  1113
#define IDS_STRING1114                  1114
#define IDS_STRING_AUTO_ADJUST          1115
#define IDS_STRING_FIXED_SIZE           1116
#define IDS_STRING_MANUAL               1117
#define IDS_STRING_ADJUST               1118
#define IDS_STRING_WIDTH                1119
#define IDS_STRING_HEIGHT               1120
#define IDS_COMBO_ALIGNMENT             1130
#define IDS_STRING_BK_LEGEND            1140
#define IDS_STRING_CURVE                1141
#define IDS_CHECK_TWO_COLOR             1150
#define IDS_STRING_OLD                  1150
#define IDS_STRING_OLD_NEW              1151
#define IDS_STRING_NEW                  1151
#define IDS_STRING_NEW_COLOR            1152
#define IDS_STRING_OLD_COLOR            1153
#define IDS_STRING_EP1                  1470
#define IDS_STRING_EP2                  1471
#define IDS_STRING_EP3                  1472
#define IDS_STRING_EP4                  1473
#define IDS_STRING_EP5                  1474
#define IDS_STRING_EP6                  1475
#define IDS_STRING_EP7                  1476
#define IDS_STRING_EP8                  1477
#define IDS_STRING_EP9                  1478
#define IDS_STRING_EP10                 1479
#define IDS_STRING_EP11                 1480
#define IDS_STRING_EP12                 1481
#define IDS_STRING_EP13                 1482
#define IDS_STRING_GENERAL_INFO         1500
#define IDS_STRING_SOFTWARE             1501
#define IDS_STRING_TIME                 1502
#define IDS_STRING_RESULT               1503
#define IDS_STRING_EXPORT_DLG           1550
#define IDS_STRING_EXPORT               1551
#define IDS_STRING_SELECT_ALL           1552
#define IDS_CHECK_SHOW_FORMULA          1580
#define IDS_BTN_COMPUTE                 1581
#define IDS_STRING_RAW                  1590
#define IDS_STRING_CORRECTION           1591
#define IDS_STRING_OUTPUT               1592
#define ID_ANALYSIS_METHODSETUP         32771
#define ID_HELP_HELPTOPICS              32771
#define ID_ANALYSIS_STARTANALYSIS       32772
#define ID_ANALYSIS_PAUSE               32773
#define ID_ANALYSIS_ABORTANALYSIS       32774
#define ID_ANALYSIS_COMPUTE             32775
#define ID_ANALYSIS_REPORT              32776
#define ID_ANALYSIS_DATALISTING         32776
#define ID_ANALYSIS_EXPORTDATA          32777
#define ID_CONTROLS_1                   32778
#define ID_CONTROLS_2                   32779
#define ID_CONTROLS_CHANGESAP           32780
#define ID_OPTIONS_PLOTSETTINGS         32781
#define ID_VIEW_FITWINDOW               32782
#define ID_VIEW_DATACURSOR              32783
#define ID_VIEW_ANALYSIS_PROGRESS       32784
#define ID_VIEW_TOOLBAR_A               32785
#define ID_SECURITY_LOGIN               32786
#define ID_SECURITY_USERACCOUNTS        32787
#define ID_LANGUAGE_CHINESE             32788
#define ID_LANGUAGE_ENGLISH             32789
#define ID_POPUP_INSERT                 32790
#define ID_VIEW_TOOLBARA                32790
#define ID_POPUP_REMOVE                 32791
#define ID_POPUP_REMOVEALL              32792
#define ID_POPUP_ADDUSER                32793
#define ID_POPUP_DELETEUSER             32794
#define ID_32795                        32795
#define ID_CONTROL                      32796
#define ID_32797                        32797
#define ID_FILE_CLOSE                   0xE102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
